---
- name: Prelim
  hosts: all
  become: yes

  tasks:
    - name: config.yml
      include_vars:
         file: config.yml


- name: Added roles
  hosts: all
  roles:
    - install_java
    - install_python
    - create_motd
    - create_user
